using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using TenantVault.BusinessLogic;
using TenantVault.Models;

namespace TenantVault.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class InventoryController(IInventoryService inventoryService) : ControllerBase
    {
        private readonly IInventoryService _inventoryService = inventoryService;

        // [ProducesResponseType] on every action documents the real response contract (including
        // the 400 that [ApiController] triggers automatically for failed model validation), so
        // the OpenAPI spec generated by AddOpenApi() reflects more than just a bare 200.
        [HttpPost("vehicle")]
        [ProducesResponseType(typeof(Guid), StatusCodes.Status201Created)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        public async Task<ActionResult<Guid>> AddVehicleAsync(
            [FromBody, Required] Vehicle vehicle,
            CancellationToken cancellationToken)
        {
            var vehicleId = await _inventoryService.AddVehicleAsync(vehicle, cancellationToken);

            // CreatedAtAction returns 201 (the correct status for a resource-creation endpoint,
            // vs. a bare 200) and builds the Location header from GetVehicleAsync's own route,
            // so it can't drift out of sync if that route template ever changes.
            return CreatedAtAction(nameof(GetVehicleAsync), new { tenantId = vehicle.TenantId, warehouseId = vehicle.WarehouseId, vehicleId }, vehicleId);
        }

        // Singular "vehicle" route: this returns exactly one resource. A missing vehicle here is
        // a genuine 404 - the specific ID doesn't exist - unlike the collection endpoints below.
        //
        // [ActionName] pins the routable action name to the full method name: MVC strips the
        // "Async" suffix by default, so without this, CreatedAtAction(nameof(GetVehicleAsync), ...)
        // above would reference a route name ("GetVehicleAsync") that doesn't actually exist
        // (the real one is "GetVehicle"), and fail at request time with "No route matches the
        // supplied values."
        [HttpGet("vehicle/{tenantId}/{warehouseId:int}/{vehicleId:guid}")]
        [ActionName(nameof(GetVehicleAsync))]
        [ProducesResponseType(typeof(Vehicle), StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<ActionResult<Vehicle?>> GetVehicleAsync(
            [FromRoute] string tenantId,
            [FromRoute] int warehouseId,
            [FromRoute] Guid vehicleId,
            CancellationToken cancellationToken)
        {
            var vehicle = await _inventoryService.GetVehicleAsync(tenantId, warehouseId, vehicleId, cancellationToken);
            return vehicle is null ? NotFound() : Ok(vehicle);
        }

        // Plural "vehicles" route: this returns a collection, so the URL communicates
        // cardinality consistently with the endpoints below.
        [HttpGet("vehicles/{tenantId}/{warehouseId:int}")]
        [ProducesResponseType(typeof(IEnumerable<Vehicle>), StatusCodes.Status200OK)]
        public async Task<ActionResult<IEnumerable<Vehicle>>> GetVehiclesByWarehouseAsync(
            [FromRoute] string tenantId,
            [FromRoute] int warehouseId,
            CancellationToken cancellationToken)
        {
            // Always 200, even with zero matches: an empty result set is a successful query, not
            // a missing resource, so it shouldn't be conflated with the point-read 404 above.
            var vehicles = await _inventoryService.GetVehiclesByWarehouseAsync(tenantId, warehouseId, cancellationToken);
            return Ok(vehicles);
        }

        [HttpGet("vehicles/{tenantId}")]
        [ProducesResponseType(typeof(IEnumerable<Vehicle>), StatusCodes.Status200OK)]
        public async Task<ActionResult<IEnumerable<Vehicle>>> GetVehiclesByTenantAsync(
            [FromRoute] string tenantId,
            CancellationToken cancellationToken)
        {
            var vehicles = await _inventoryService.GetVehiclesByTenantAsync(tenantId, cancellationToken);
            return Ok(vehicles);
        }
    }
}
